version: '3'

services:
  php:
    build:
      dockerfile: ./docker/images/php/Dockerfile
      context: .
    tty: true
    restart: on-failure
    container_name: php
    links:
      - mysql
    volumes:
      - './:/project'
      - './docker/config/php/php.ini:/usr/local/etc/php/php.ini'
    env_file:
      - '.env'
  mysql:
    build:
      dockerfile: ./docker/images/mysql/Dockerfile
      context: .
    tty: true
    restart: on-failure
    container_name: mysql
    ports:
      - '3306:3306'
    volumes:
      - 'db_data:/var/lib/mysql'
      - './:/project'
    env_file:
      - '.env'
  nginx:
    build:
      dockerfile: ./docker/images/nginx/Dockerfile
      context: .
    tty: true
    restart: on-failure
    container_name: nginx
    volumes:
      - './:/project'
      - './docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './docker/config/nginx/project.conf:/etc/nginx/project.conf'
    ports:
      - '80:80'
    links:
      - php
      - mysql
    env_file:
      - '.env'

volumes:
  db_data: { }