FROM php:7.4-fpm

RUN apt-get update
RUN apt-get install -y curl wget git libffi-dev libcurl4-openssl-dev openssl libssl-dev libz-dev libjpeg62-turbo-dev libfreetype6-dev libmcrypt-dev libonig-dev libpq-dev libpng-dev zlib1g-dev libzip-dev

RUN docker-php-ext-install mbstring && docker-php-ext-configure mbstring
RUN docker-php-ext-install zip && docker-php-ext-configure zip
RUN docker-php-ext-install curl && docker-php-ext-configure curl
RUN docker-php-ext-install shmop && docker-php-ext-configure shmop
RUN docker-php-ext-install gettext && docker-php-ext-configure gettext
RUN docker-php-ext-install fileinfo && docker-php-ext-configure fileinfo
RUN docker-php-ext-install ffi && docker-php-ext-configure ffi
RUN docker-php-ext-install ftp && docker-php-ext-configure ftp

RUN docker-php-ext-install mysqli pdo pdo_mysql && \
    docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd && \
    docker-php-ext-configure mysqli --with-mysqli=mysqlnd

RUN apt-get install -y \
        && pecl install mcrypt-1.0.3 \
	&& docker-php-ext-enable mcrypt \
        && docker-php-ext-install -j$(nproc) iconv \
	&& docker-php-ext-configure gd --with-freetype --with-jpeg \
        && docker-php-ext-install -j$(nproc) gd

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN apt-get update && apt-get install -y libmemcached-tools libzip-dev zlib1g libmemcached-dev bzip2

RUN git clone -b master https://github.com/php-memcached-dev/php-memcached /usr/src/php/ext/memcached \
    && docker-php-ext-configure /usr/src/php/ext/memcached \
        --disable-memcached-sasl \
    && docker-php-ext-install /usr/src/php/ext/memcached \
    && rm -rf /usr/src/php/ext/memcached

RUN apt-get install -y libc-client-dev libkrb5-dev libgmp-dev
RUN docker-php-ext-configure imap --with-kerberos --with-imap-ssl && docker-php-ext-install imap
RUN docker-php-ext-install gmp && docker-php-ext-configure gmp
RUN docker-php-ext-install exif && docker-php-ext-configure exif

RUN apt-get install -y libbz2-dev zlib1g-dev
RUN docker-php-ext-install bz2 && docker-php-ext-configure bz2

RUN pecl install xdebug-2.8.0
ENV XDEBUG_EXT zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20190902/xdebug.so
RUN alias php_xdebug="php -d$XDEBUG_EXT vendor/bin/phpunit"